#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os


def popen(txt):
    for l in os.popen(txt).readlines():
        print(l)


popen("rm -fR __pycache__ *~ bin/*~ env tar")
