#!/usr/bin/env python3
# pylint: disable=E1101,C0116,C0413
# This file is placed in the Public Domain.


"lintify"


import os

os.environ["PYTHONPATH"] = "."

skip = ["---", "===", "Your code"]
TXT = 'pylint -d "C0116,C0115,W0613,W0212,R0902,R0903,R0904" %s'


def doskip(txt):
    for name in skip:
        if name in txt:
            return True
    return False


def payload(dname):
    for fnm in os.listdir(dname):
        if fnm.endswith("~"):
            continue
        fnn = "%s/%s" % (dname, fnm)
        for line in os.popen(TXT % fnn).readlines():
            if not line or doskip(line):
                continue
            liner = line.strip()
            if liner:
                print(liner)


def main():
    payload("dev")
    payload("src/oplib")
    payload("src/botlib")
    payload("src/rssbot")


main()
