#!/usr/bin/env python3
# This file is placed in the Public Domain.


import sys
import os
import shutil


SKIP = ["..", "__", ".git"]

try:
    source = sys.argv[1]
    sedstring = sys.argv[2]
except IndexError:
    print("sed <dir> <sedstring>")
    os._exit(1)


def gethighest(ddir, ffile):
    highest = 0
    for i in os.listdir(ddir):
        if os.path.isdir(ddir + os.sep + i) and ffile in i:
            try:
                seqnr = i.split('.')[-1]
            except IndexError:
                continue
            try:
                if int(seqnr) > highest:
                    highest = int(seqnr)  
            except ValueError:
                pass
    ffile += "." + str(highest + 1)
    print(ffile)
    return ffile   


def dosed(filename, sedstring):
    f = open(filename, 'r')
    tmp = filename + '.tmp'
    fout = open(tmp, 'w')
    seds = sedstring.split('/')
    if seds:
        fr = seds[1].replace('\\', '')
        to = seds[2].replace('\\', '')
        try:
            for line in f:
                l = line.replace(fr,to)
                fout.write(l)
        finally:
            fout.flush()
            fout.close()
    try:
        os.rename(tmp, filename)
    except WindowsError:
        os.remove(filename)
        os.rename(tmp, filename)


def doskip(txt):
    for sk in SKIP:
        if sk in txt:
            return True
    return False


def doreplace(ddir, sedstring):
    ddir = os.path.join(ddir, "")
    for f in os.listdir(ddir):
        if doskip(f):
            continue
        try:
            dosed(ddir + os.sep + f, sedstring)
        except IOError as ex:
            if 'Is a dir' in str(ex):
                doreplace(ddir + os.sep + f, sedstring)


target = gethighest(os.getcwd(), source)


try:
    shutil.copytree(source, target)
except OSError:
    os._exit(1)


doreplace(target, sedstring)
