#!/usr/bin/env python3
# This file is placed in the Public Domain.


import os
import sys


sys.path.insert(0, os.getcwd())


def getlist():
    return [x.strip() for x in open("CFG", "r").readlines()[-1].split(",")]


SKIP = ["test_", "not found"]
TODO = getlist()


def doskip(txt):
    for name in SKIP:
        if name in txt:
            return True
    return False


def popen(txt):
    for line in os.popen(txt).readlines():
        l = line.rstrip()
        if doskip(l):
            continue
        print(l)
        sys.stdout.flush()


for td in TODO:
    print("## testing %s" % td)
    os.chdir("src/%s" % td)
    if os.path.exists("bin/test"):
        popen("bin/test")
    os.chdir("..")
    os.chdir("..")
